// =====================================================================
// Deutsch. Schweizer Konvention: «ss» statt «ß».
//
// Fehlende Schlüssel fallen auf Englisch zurück; der Build meldet sie.
// NICHT übersetzen: `file`, URLs, Feldnamen des Formulars.
//
// Lange Komposita in Grossüberschriften brauchen ein weiches Trennzeichen
// (&shy;). Die Anzeige-Schrift ist versal und sehr gross; ohne Trennung
// ist «Dateninfrastruktur» auf einem 390-px-Display breiter als die
// Spalte. &shy; ist im Gegensatz zu hyphens:auto nicht davon abhängig,
// ob der Browser ein deutsches Trennwörterbuch mitbringt.
// =====================================================================

export default {
  locale: 'de',
  localeName: 'Deutsch',
  htmlLang: 'de-CH',

  brand: { sub: 'Beratung', location: 'Basel, Schweiz' },

  nav: { menu: 'Menü', services: 'Leistungen', work: 'Referenzen', about: 'Über mich', enquire: 'Anfragen' },

  ui: {
    skip: 'Zum Inhalt springen',
    closeMenu: 'Menü schliessen',
    toggleTheme: 'Farbschema wechseln',
    language: 'Sprache',
    share: 'Diese Seite teilen',
    shareEmail: 'E-Mail',
    copyLink: 'Link kopieren',
    copied: 'Kopiert',
    allArticles: 'Alle Beiträge',
    allServices: 'Alle Leistungen',
    allProjects: 'Alle Projekte',
    allInvolvement: 'Alle Engagements',
    aboutFounder: 'Über den Gründer',
    getInTouch: 'Kontakt',
    startConversation: 'Gespräch beginnen',
    read: 'Lesen',
    searchArticles: 'Beiträge durchsuchen',
    filterAll: 'Alle',
  },

  menu: {
    home: 'Startseite', practice: 'Die Praxis', workGroup: 'Referenzen', elsewhere: 'Anderswo',
    projects: 'Projekte', journal: 'Journal', involvement: 'Engagement',
    note: 'Open-Source-Werkzeuge für regulatorisches Reporting, Schweizer Rechtsdaten und Interoperabilität im Gesundheitswesen.',
    enquireNow: 'Jetzt anfragen', impressum: 'Impressum',
  },

  footer: {
    blurb: 'Datenintegration, Governance und Lifecycle-Management für regulierte Branchen. Basel, Schweiz.',
    colPractice: 'Praxis', colWork: 'Referenzen', colContact: 'Kontakt',
    rights: 'Alle Rechte vorbehalten',
  },

  pages: {
    index: {
      file: 'index.html',
      title: 'Arfa Digital Consulting | Dateninfrastruktur für regulierte Branchen',
      description: 'Arfa Digital Consulting — Datenintegration, Governance und Interoperabilität im Gesundheitswesen aus Basel, Schweiz. Gegründet von Benjamin Arfa.',
      eyebrow: 'Beratung aus Basel, Schweiz',
      display: 'Daten&shy;infrastruktur für regulierte Branchen',
      lead: 'Spezialisierte Beratung in Datenintegration, Governance und Lifecycle-Management &mdash; für Regulatory Technology und das Gesundheitswesen, wo Korrektheit keine Option ist.',
      facts: [
        { k: 'Standort', v: 'Basel, Schweiz' },
        { k: 'Sprachen', v: 'Französisch &middot; Deutsch &middot; Englisch &middot; Spanisch' },
        { k: 'Status', v: 'Offen für Mandate', dot: true },
      ],
      practiceLabel: '01 &mdash; Die Praxis',
      practiceHeading: 'Technik, die dem Audit standhält',
      practiceBody: [
        'Arfa Digital Consulting fördert die digitale Transformation durch <strong>IT- und KI-Lösungen, Softwareentwicklung, Datenanalyse und strategische Beratung</strong> &mdash; abgestimmt auf Schweizer und europäische regulatorische Anforderungen.',
        'Dahinter steht <strong>Benjamin Arfa</strong>: Ingenieur, Technical Manager bei HL7 Schweiz und Mitgründer von <strong>BIRDBench Ltd</strong>. Neun Jahre Metadatenmodellierung für EZB und BFS, FHIR-Datenmodellierung für das Schweizer Gesundheitswesen, Open-Source-Werkzeuge für BIRD und Fertigungsdaten in den Life Sciences.',
      ],
      quote: 'Gemeinsame Infrastruktur statt lizenzierter Silos. Transparente Regeln statt Blackboxes.',
      quoteAttr: 'Über den Aufbau offener Regulierungswerkzeuge',
      servicesLabel: '02 &mdash; Leistungen',
      servicesHeading: 'Drei Säulen',
      workLabel: '03 &mdash; Ausgewählte Referenzen',
      workHeading: 'Open Source und Produktion',
      involvementLabel: '04 &mdash; Engagement',
      involvementHeading: 'Standards und Community',
      ctaHeading: 'Arbeiten wir zusammen',
      ctaBody: 'Sie suchen Orientierung bei Dateninitiativen, Systemintegration oder Interoperabilität? Jedes Mandat beginnt mit einem Erstgespräch.',
    },

    about: {
      file: 'about.html',
      title: 'Über mich | Benjamin Arfa, Arfa Digital Consulting',
      description: 'Benjamin Arfa — Daten- und Software-Ingenieur in Basel. Neun Jahre in Gesundheitswesen, Regulatory Technology und Data Governance.',
      eyebrow: 'Der Gründer',
      pageTitle: 'Benjamin Arfa',
      sub: 'Daten- und Software-Ingenieur in Basel. Neun Jahre in Gesundheitswesen, Regulatory Technology und unternehmensweiter Governance &mdash; Gründer von Arfa Digital Consulting, Mitgründer von BIRDBench Ltd.',
      bgLabel: '01 &mdash; Hintergrund',
      bgHeading: 'Beruflicher Hintergrund',
      bgBody: [
        'Ich bin spezialisiert auf <strong>Datenintegration</strong>, <strong>Governance</strong> und <strong>Lifecycle-Management</strong> in Regulatory Technology und im Gesundheitswesen. In über neun Jahren habe ich tiefe Expertise darin aufgebaut, Datenstrategien und technische Lösungen umzusetzen, die einer Prüfung standhalten.',
        'In <strong>Datenstrategie und Architektur</strong> liegt mein Fokus auf umfassendem Lifecycle-Management durch wirksame Datenmodellierung und technische Umsetzung &mdash; robuste, geschäftsorientierte Systeme und Organisationen, die wirklich datengetrieben arbeiten.',
        'Meine technische Arbeit umfasst <strong>Requirements Engineering</strong> als Brücke zwischen Fach- und Technikteams sowie <strong>Software Engineering</strong> für skalierbare Datenanwendungen. Als <strong>Technical Manager bei HL7 Schweiz</strong> (FHIR-CH) treibe ich die Standardisierung von Gesundheitsdaten voran. Als Mitgründer von <strong>BIRDBench Ltd</strong> bringe ich Innovation in die RegTech, und als <strong>Eclipse-Contributor</strong> entwickle ich Regulierungswerkzeuge offen.',
      ],
      glanceLabel: 'Auf einen Blick',
      glance: [
        { k: 'Standort', v: 'Basel, Schweiz' },
        { k: 'Sprachen', v: 'Französisch &middot; Deutsch &middot; Englisch &middot; Spanisch' },
        { k: 'Standards', v: 'HL7 FHIR &middot; SDMX &middot; BIRD' },
        { k: 'Mitgründer', v: 'BIRDBench Ltd' },
        { k: 'Open Source', v: 'Contributor der Eclipse Foundation' },
      ],
      quote: 'Gemeinsame Infrastruktur schlägt lizenzierte Silos &mdash; transparente Regeln schlagen Blackboxes.',
      quoteAttr: 'Warum die Werkzeuge quelloffen sind',
      careerLabel: '02 &mdash; Werdegang',
      careerHeading: 'Beruflicher Werdegang',
      career: [
        { when: 'Mai 2026 &mdash;', role: 'Mitgründer', where: 'BIRDBench Ltd', desc: 'Innovation in die RegTech bringen.' },
        { when: 'Apr. 2026 &mdash;', role: 'Technical Manager', where: 'HL7 Schweiz', desc: 'Standardisierung von Gesundheitsdaten für FHIR-CH &mdash; Umsetzungsleitfäden, Arbeitsgruppen zur Interoperabilität und Schweizer Standards für den Gesundheitsdatenaustausch.' },
        { when: 'Okt. 2025 &mdash;', role: 'Business Analyst', where: 'Bachem', desc: 'Requirements Engineering für pharmazeutische und biotechnologische Daten in der Life-Sciences-Fertigung &mdash; Systemintegration, Lifecycle-Management und operatives Reporting in Forschung und Produktion.' },
        { when: 'Feb. 2025 &mdash;', role: 'Head of Development', where: 'BIRD Software Solutions', desc: 'Leitung von Softwareentwicklung und technischer Strategie für Regulatory Technology &mdash; quelloffene Dateninfrastruktur nach dem BIRD-Standard.' },
        { when: '2022 &ndash; 2024', role: 'Product Owner, Daten &amp; Integration', where: 'Bluespace Ventures', desc: 'Semantische Datenintegration, FHIR-Datenmodellierung, MDM-Frameworks. Mitarbeit bei HL7 Schweiz und in der SNOMED French Translation Group.' },
        { when: '2020 &ndash; 2022', role: 'Research Analyst, Metadaten', where: 'EZB &amp; BFS', desc: 'Metadatenmodellierung für die Bankenaufsicht im BIRD/SDD-Team, SDMX-Methodik, Prozessautomatisierung und API-Integration für Metadaten-Repositorien.' },
        { when: '2017 &ndash; 2020', role: 'Data Scientist &amp; ML-Forscher', where: 'RWTH Aachen &middot; rheindata &middot; CWD &middot; Boralex', desc: 'Machine-Learning-Forschung, explorative Datenanalyse und datengetriebene Anwendungen in Windenergie und Industrie.' },
      ],
      skillsLabel: '03 &mdash; Kompetenzen',
      skillsHeading: 'Kernkompetenzen',
      skills: [
        { label: 'Daten', h: 'Daten &amp; Analytics', tags: ['Datenintegration', 'Governance', 'Datenmodellierung', 'Machine Learning', 'ETL / ELT'] },
        { label: 'Entwicklung', h: 'Engineering', tags: ['Python', 'Go', 'Docker', 'REST-APIs', 'Cloud'] },
        { label: 'Standards', h: 'Gesundheitswesen &amp; Standards', tags: ['HL7 FHIR', 'SDMX', 'MDM', 'Interoperabilität', 'BIRD'] },
      ],
      personalLabel: '04 &mdash; Abseits der Arbeit',
      personalHeading: 'Der Mensch dahinter',
      personalBody: [
        'Ich bin <strong>Benni</strong> &mdash; eine französisch-deutsch-arabische Seele, derzeit in Basel.',
        'Musik ist meine Leidenschaft, Software mein Handwerk, und das Schreiben begleitet mich seit dem fünften Gymnasialjahr. Angefangen habe ich mit Zeichnen, Malerei und Kalligrafie, später kam die Poesie dazu. Heute schreibe ich Prosodie und melde mich hin und wieder zu Wort.',
        'Ich äussere mich gerne zu <strong>Souveränität, Technologie und Solidarität</strong>.',
      ],
      personal: [
        { k: 'Musik', v: 'spielen &middot; hören &middot; jammen' },
        { k: 'Software', v: 'das tägliche Handwerk' },
        { k: 'Schreiben', v: 'Poesie &middot; Prosodie' },
        { k: 'Interessen', v: 'Souveränität &middot; Technologie &middot; Solidarität' },
      ],
      ctaHeading: 'Zusammenarbeiten?',
      ctaBody: 'Ich tausche mich jederzeit gerne mit Fachkolleginnen und -kollegen über Datenfragen und Möglichkeiten aus.',
    },

    services: {
      file: 'services.html',
      title: 'Leistungen | Arfa Digital Consulting',
      description: 'Software Engineering, Interoperabilität im Gesundheitswesen und Metadatenarchitektur — spezialisierte Beratung für Schweizer und europäische Regulierung.',
      eyebrow: 'Was ich anbiete',
      pageTitle: 'Leistungen',
      sub: 'Arfa Digital Consulting fördert die digitale Transformation durch IT- und KI-Lösungen, Softwareentwicklung, Datenanalyse und strategische Beratung &mdash; abgestimmt auf Schweizer und europäische regulatorische Anforderungen.',
      pillarsLabel: '01 &mdash; Spezialleistungen',
      pillarsHeading: 'Drei Säulen',
      pillars: [
        { label: 'Säule 01 &mdash; Software Engineering', body: 'Skalierbare Datenanwendungen und Systemintegration. Vom Requirements Engineering bis zum Betrieb, als Brücke zwischen Fach- und Technikteams.', tags: ['Individuelle Anwendungen', 'API-Design', 'Docker-Containerisierung', 'Requirements Engineering', 'Cloud-Lifecycle-Management'] },
        { label: 'Säule 02 &mdash; Interoperabilität im Gesundheitswesen', body: 'Technical Manager bei <strong>HL7 Schweiz</strong> (FHIR-CH), treibend bei der Standardisierung von Gesundheitsdaten. Schwerpunkt auf semantischer Datenintegration und Stammdatenmanagement.', tags: ['HL7-FHIR-Umsetzung', 'Semantische Datenintegration', 'Stammdatenmanagement', 'Standardisierung im Gesundheitswesen', 'Systemintegration'] },
        { label: 'Säule 03 &mdash; Metadatenarchitektur', body: 'Umfassendes Metadatenmanagement und Datenarchitektur. Robuste, geschäftsorientierte Systeme mit wirksamen Governance-Rahmenwerken.', tags: ['Metadatenmanagement', 'Data Governance', 'SDMX &amp; BIRD', 'Lifecycle-Strategie', 'Geschäftsorientierte Lösungen'] },
      ],
      processLabel: '02 &mdash; Zusammenarbeit',
      processHeading: 'So arbeite ich',
      process: [
        { label: 'Schritt 01', h: 'Verstehen', p: 'Ihre Herausforderungen und Ihren Geschäftskontext erfassen &mdash; Erstgespräch, Stakeholder-Mapping.' },
        { label: 'Schritt 02', h: 'Entwerfen', p: 'Lösungen im Einklang mit Ihren Zielen &mdash; Datenmodelle, Integrationstopologie, Governance.' },
        { label: 'Schritt 03', h: 'Entwickeln', p: 'Robuste, skalierbare Umsetzung &mdash; Python, Go, FHIR, Docker, CI.' },
        { label: 'Schritt 04', h: 'Liefern', p: 'Inbetriebnahme und Begleitung &mdash; Übergabe, Dokumentation, beratendes Mandat.' },
      ],
      extrasLabel: '03 &mdash; Ebenfalls verfügbar',
      extrasHeading: 'Weitere Leistungen',
      extrasTag: 'Zusätzlich',
      extras: [
        { h: 'IT-Beratung', p: 'Strategische Orientierung bei Technologieentscheiden, Infrastrukturoptimierung und digitaler Transformation.' },
        { h: 'Mehrsprachige Kommunikation', p: 'Brückenbau zwischen französischen, deutschen, englischen und spanischen Kontexten.' },
        { h: 'Datenmodellierung', p: 'Konzeptionelle, logische und physische Modellierung für Datenbanken und Warehouses.' },
        { h: 'ML-Beratung', p: 'Machine-Learning-Strategie, Begleitung der Modellentwicklung und KI-Lösungsarchitektur.' },
      ],
      quote: 'Jedes Mandat beginnt mit einem Erstgespräch &mdash; und einer ehrlichen Antwort darauf, ob ich die richtige Person dafür bin.',
      quoteAttr: 'Wie Mandate beginnen',
      faqLabel: '04 &mdash; Fragen',
      faqHeading: 'Häufige Fragen',
      faq: [
        { q: 'An welchen Projekten arbeiten Sie typischerweise?', a: 'Data Engineering, Interoperabilität im Gesundheitswesen und Regulatory Technology. Die Bandbreite reicht von HL7-FHIR-Integrationspipelines und BIRD-Werkzeugen für das regulatorische Reporting bis zu Metadatenarchitekturen und Stammdatenlösungen.' },
        { q: 'Arbeiten Sie auch mit Kundinnen und Kunden ausserhalb der Schweiz?', a: 'Ja. Ich bin in Basel ansässig, arbeite aber regelmässig mit Teams in ganz Europa und remote mit internationalen Kunden. Mein mehrsprachiger Hintergrund (Französisch, Deutsch, Englisch, Spanisch) erleichtert die Verständigung in heterogenen Teams.' },
        { q: 'Wie sieht Ihr übliches Mandatsmodell aus?', a: 'Mandate folgen vier Schritten: verstehen, entwerfen, entwickeln, liefern. Ich biete projektbasierte Beratung mit klaren Ergebnissen ebenso wie laufende beratende Mandate. Jedes Mandat beginnt mit einem Erstgespräch.' },
        { q: 'Unterstützen Sie auch bestehende Systeme oder nur Neuentwicklungen?', a: 'Beides. Ein wesentlicher Teil meiner Arbeit besteht darin, bestehende Datensysteme zu modernisieren, Pipelines zu verbessern und neue Standards in gewachsene Infrastruktur zu integrieren &mdash; einschliesslich HL7 v2, proprietärer KIS-Exporte und bestehender Reporting-Rahmenwerke.' },
        { q: 'Wie gehen Sie mit Datenschutz und Compliance um?', a: 'Datenschutz ist von Anfang an eingeplant: Schweizer und EU-Datenschutzanforderungen, DSGVO-Konformität, Vertraulichkeit von Gesundheitsdaten und sichere Verarbeitung im regulatorischen Reporting.' },
      ],
      ctaHeading: 'Bereit für ein Projekt?',
      ctaBody: 'Lassen Sie uns besprechen, wie ich Sie bei Ihren Daten- und Technologiezielen unterstützen kann. Briefings, halbfertige Ideen und Erstkontakte sind gleichermassen willkommen.',
    },

    projects: {
      file: 'projects.html',
      title: 'Projekte | Arfa Digital Consulting',
      description: 'Open-Source-Werkzeuge und Datenanwendungen in Regulatory Technology, Gesundheitswesen und GovTech — von Benjamin Arfa.',
      eyebrow: 'Was ich gebaut habe',
      pageTitle: 'Projekte',
      sub: 'Open-Source-Werkzeuge, Datenanwendungen und Software Engineering in Regulatory Technology, Gesundheitswesen und GovTech.',
      currentLabel: '01 &mdash; Aktuell',
      currentHeading: 'Open Source und Produktion',
      quote: 'Regulatorisches Reporting betrifft jede Bank &mdash; und über die Banken am Ende alle. Genau deshalb entsteht dieses Werkzeug offen.',
      quoteAttr: 'Über offene Standards',
      archiveLabel: '02 &mdash; Archiv',
      archiveHeading: 'Frühere Arbeiten',
      archiveTag: 'Archiv',
      ctaHeading: 'Interesse an Zusammenarbeit?',
      ctaBody: 'Ich spreche jederzeit gerne über neue Projekte, Beiträge zu Open Source oder Kooperationsmöglichkeiten.',
      visitDashboard: 'Zum Dashboard',
      visitSite: 'consultaition.ch besuchen',
      visitDemo: 'Demo öffnen',
      viewGitHub: 'Auf GitHub ansehen',
      entries: [
        {
          anchor: 'swiss-law', n: '01', role: 'Maintainer &middot; GovTech',
          h: 'Swiss Law Collection',
          kicker: 'Schweizer Bundes- und Kantonsrecht als abfragbarer Datensatz',
          body: [
            'Ein Dashboard über die schweizerische Bundes- und Kantonsgesetzgebung sowie eine statische, nur lesende JSON-, CSV- und SDMX-API direkt aus GitHub Pages. Rechtsgebiete sind über den Bund und alle 26 Kantone harmonisiert, sodass Bundes- und Kantonserlasse auf derselben Achse vergleichbar werden.',
            'Gesetze als Daten statt als PDF zu veröffentlichen heisst, dass nachgelagerte Systeme dagegen getestet werden können &mdash; und Atom- und RSS-Feeds machen eine Gesetzesänderung zu etwas, das Software abonnieren kann.',
          ],
          details: [
            { k: 'Abdeckung', v: '34’443 Erlasse &mdash; Bund und 26 Kantone' },
            { k: 'Artikel', v: '824’663 erfasst' },
            { k: 'Formate', v: 'JSON &middot; CSV &middot; SDMX' },
            { k: 'Quellen', v: 'Fedlex (Bund) &middot; LexFind (Kantone)' },
            { k: 'Verifikation', v: 'Veröffentlichter Abgleich mit BADAC und chstat' },
            { k: 'Pipeline', v: '<a class="link" href="https://github.com/benjamin-arfa/swiss-law" target="_blank" rel="noopener">github.com/benjamin-arfa/swiss-law</a>' },
          ],
          tags: ['Open Data', 'SDMX', 'JSON-API', 'Python'],
          href: 'https://swiss-law-as-source.github.io/', cta: 'visitDashboard',
        },
        {
          anchor: 'consultaition', n: '02', role: 'Maintainer &middot; GovTech',
          h: 'consultaition',
          kicker: 'Generator für Schweizer Vernehmlassungsberichte',
          body: [
            'Automatisiert die Erstellung eidgenössischer <em>Ergebnisberichte</em> aus strukturierten Excel-Daten. Anbieterunabhängige LLM-Optimierung, trainiert auf echten Vernehmlassungsdaten des Bundes &mdash; ohne Herstellerbindung.',
          ],
          details: [
            { k: 'Editor', v: 'Interaktives Canvas, Absatz für Absatz' },
            { k: 'API', v: 'REST-Endpunkt zur programmatischen Erzeugung' },
            { k: 'Sprachen', v: 'Deutsch &middot; Französisch &middot; Italienisch' },
            { k: 'Ausgabe', v: 'Fussnotenverwaltung und Export' },
          ],
          tags: ['Python', 'FastAPI', 'LLM', 'GovTech'],
          href: 'https://consultaition.ch', cta: 'visitSite',
        },
        {
          anchor: 'freebird', n: '03', role: 'Contributor &middot; RegTech',
          h: 'Eclipse FreeBIRD tools',
          kicker: 'Werkzeuge, die BIRD als offenen Standard zugänglich machen',
          body: [
            'Ein quelloffenes Toolkit für das Banks’ Integrated Reporting Dictionary &mdash; den Standard, der die Meldevorschriften und Vorlagen definiert, mit denen europäische Banken Daten an die Aufsicht liefern.',
          ],
          details: [
            { k: 'Toolkit', v: 'GUI für Dictionaries und Mappings' },
            { k: 'Laufzeit', v: 'Docker-Containerisierung' },
            { k: 'Modelle', v: 'BIRD-Modelle validieren und transformieren' },
            { k: 'Installation', v: '<span class="mono">pip install pybirdai</span>' },
          ],
          tags: ['Python', 'Docker', 'NLP', 'RegTech'],
          href: 'https://github.com/eclipse-efbt/efbt', cta: 'viewGitHub',
        },
        {
          anchor: 'law-as-code', n: '04', role: 'Contributor &middot; GovTech',
          h: 'Law as Code',
          kicker: 'Schweizer Steuer- und Sozialnormen als ausführbare Logik',
          body: [
            'Entstanden am <strong>Open Legal Lab 2026</strong> in Magglingen: eine Pipeline, die schweizerisches Bundesrecht in maschinell ausführbaren Code überführt. Die Artikel werden über SPARQL aus Fedlex geholt, von einer DSPy-Pipeline nach OpenFisca oder Catala transformiert und validiert, indem das Ergebnis gegen Testpersonen mit bekannten Werten ausgeführt wird.',
            'Eine Frage in Alltagssprache geht an einen Fallklassifikator, der die einschlägigen Variablen über einen Rechtsindex auflöst und auf einer OpenFisca-Engine ausführt &mdash; mit dem eidgenössischen Steuer- und Sozialsystem ebenso wie mit dem Berner Stipendienrecht. Geschlossen wird die Lücke zwischen einer per Volksabstimmung geänderten Norm und der Verwaltungssoftware, die sie umsetzen muss.',
          ],
          details: [
            { k: 'Quelle', v: 'Fedlex-SPARQL-Endpunkt &middot; ELI-Bezeichner' },
            { k: 'Zielsprachen', v: 'OpenFisca &middot; Catala' },
            { k: 'Pipeline', v: 'DSPy-Chain-of-Thought, BootstrapFewShot-Optimierung' },
            { k: 'Bereiche', v: 'AHV-Beiträge &middot; direkte Bundessteuer &middot; Berner Stipendien' },
            { k: 'Validierung', v: 'Erzeugter Code gegen Testpersonen ausgeführt' },
            { k: 'Code', v: '<a class="link" href="https://github.com/OpenLegalLab/law_as_code" target="_blank" rel="noopener">github.com/OpenLegalLab/law_as_code</a>' },
          ],
          tags: ['DSPy', 'OpenFisca', 'Catala', 'LLM', 'GovTech'],
          href: 'https://vps-13d3e726.vps.ovh.net/oll/', cta: 'visitDemo',
        },
      ],
      archive: [
        { h: 'fhir.ch', p: 'Die Publikationsplattform der Schweizer FHIR-Implementierungsleitfäden, betreut über HL7 Schweiz, wo ich Technical Manager für FHIR-CH bin.', href: 'https://fhir.ch' },
        { h: 'go-detective', p: 'Native Desktop-Anwendung (Go und Wails) für KYC-Prüfungen, AML-Screening und PEP-/Sanktionsabgleich. Supabase-Backend.', href: 'https://github.com/benjamin-arfa/go-detective' },
      ],
    },

    involvement: {
      file: 'involvement.html',
      title: 'Engagement | Arfa Digital Consulting',
      description: 'Standards- und Community-Arbeit — HL7 Schweiz, fhir.ch, BIRD Software Solutions, Eclipse Foundation und BIRDBench Ltd.',
      eyebrow: 'Community &amp; Beiträge',
      pageTitle: 'Engagement',
      sub: 'Beiträge zu Fach-Communities und Standardisierungsorganisationen &mdash; in Zusammenarbeit mit <a class="link" href="https://www.eseha.ch" target="_blank" rel="noopener">ESEHA</a>, HL7 Schweiz, der Eclipse Foundation und dem BIRD-Ökosystem.',
      orgsLabel: '01 &mdash; Organisationen',
      orgsHeading: 'Wo ich mitwirke',
      quote: 'Standardisierung ist langsam und undankbar &mdash; und das Einzige, was Systeme ein Jahrzehnt später noch miteinander sprechen lässt.',
      quoteAttr: 'Warum Standards',
      whyLabel: '02 &mdash; Beweggründe',
      whyHeading: 'Warum Community zählt',
      whyTag: 'Warum',
      why: [
        { h: 'Wissensaustausch', p: 'Erfahrungen zu teilen und von Fachkolleginnen und -kollegen zu lernen beschleunigt Innovation und hilft, komplexe Probleme gemeinsam zu lösen.' },
        { h: 'Standardentwicklung', p: 'Mitarbeit an Standards sichert Interoperabilität, verringert Fragmentierung und schafft die Grundlage für tragfähige Lösungen.' },
        { h: 'Wirkung in der Branche', p: 'Aktive Mitwirkung in Fach-Communities prägt die Zukunft des Gesundheitsdatenmanagements und der Technologieadoption.' },
      ],
      ctaHeading: 'Vernetzen?',
      ctaBody: 'Ich tausche mich jederzeit gerne aus &mdash; über Datenfragen, geteiltes Wissen oder mögliche Zusammenarbeit.',
      entries: [
        {
          anchor: 'hl7', n: '01', role: 'Technical Manager', h: 'HL7 Schweiz',
          kicker: 'Health Level Seven &mdash; die globale Instanz für Interoperabilität im Gesundheitswesen',
          body: ['Technical Manager bei HL7 Schweiz (FHIR-CH), treibend bei der Standardisierung von Gesundheitsdaten in der Schweiz. HL7 setzt die globalen Standards für die Interoperabilität von Gesundheitsinformationssystemen; <strong>hl7.ch</strong> ist die Schweizer Affiliate, und auf <strong>fhir.ch</strong> werden die Schweizer FHIR-Implementierungsleitfäden veröffentlicht.'],
          details: [
            { k: 'Verein', v: '<a class="link" href="https://www.hl7.ch/de/" target="_blank" rel="noopener">hl7.ch</a>' },
            { k: 'Leitfäden', v: '<a class="link" href="https://fhir.ch" target="_blank" rel="noopener">fhir.ch</a>' },
            { k: 'Schwerpunkt', v: 'FHIR-Umsetzungsleitfäden, Arbeitsgruppen zur Interoperabilität, Schweizer Standards für den Gesundheitsdatenaustausch' },
          ],
          tags: ['HL7 FHIR', 'Interoperabilität', 'Standards'],
          href: 'https://fhir.ch', cta: 'fhir.ch besuchen',
        },
        {
          anchor: 'bird-software', n: '02', role: 'Head of Development', h: 'BIRD Software Solutions',
          kicker: 'Regulatorische Dateninfrastruktur auf Basis eines offenen Standards',
          body: ['Leitung von Softwareentwicklung und technischer Strategie für Regulatory Technology &mdash; quelloffene Dateninfrastruktur nach dem BIRD-Standard, dem Banks’ Integrated Reporting Dictionary des europäischen Aufsichtsreportings.'],
          details: [],
          tags: ['RegTech', 'BIRD', 'Open Source'],
          href: 'https://github.com/BIRD-Software-Solutions', cta: 'Auf GitHub ansehen',
        },
        {
          anchor: 'eclipse', n: '03', role: 'Contributor', h: 'Eclipse Foundation',
          kicker: 'Open Source als öffentliches Gut',
          body: ['Contributor der Eclipse Foundation über <strong>Eclipse EFBT</strong>, die Heimat der FreeBIRD-Werkzeuge. Regulatorisches Reporting betrifft jede Bank &mdash; und über die Banken am Ende alle. Diese Werkzeuge offen und unter herstellerneutraler Governance zu bauen bedeutet gemeinsame Infrastruktur statt lizenzierter Silos und transparente Regeln statt Blackboxes.'],
          details: [],
          tags: ['Eclipse EFBT', 'Offene Governance', 'Dokumentation'],
          href: 'https://www.eclipse.org', cta: 'eclipse.org besuchen',
        },
        {
          anchor: 'birdbench', n: '04', role: 'Mitgründer', h: 'BIRDBench Ltd',
          kicker: 'Innovation in die RegTech bringen',
          body: ['Mitgründer von BIRDBench Ltd &mdash; offene, benchmarkgetriebene Ansätze für Regulatory Technology im BIRD-Ökosystem.'],
          details: [],
          tags: ['RegTech', 'Benchmarking'],
          href: 'https://github.com/BIRD-Software-Solutions', cta: 'Verwandte Arbeiten',
        },
        {
          anchor: 'cmda', n: '05', role: 'Mitglied', h: 'CMDA',
          kicker: 'Conseil Mondial de la Diaspora Alg&eacute;rienne',
          body: ['Mitglied des Weltrats der algerischen Diaspora &mdash; Vertretung der Diaspora, Kulturaustausch, internationale Zusammenarbeit und Gemeinschaftsinitiativen.'],
          details: [],
          tags: ['Community', 'Kulturaustausch'],
          href: 'https://cmda.world', cta: 'cmda.world besuchen',
        },
      ],
    },

    contact: {
      file: 'contact.html',
      title: 'Kontakt | Arfa Digital Consulting',
      description: 'Kontakt zu Benjamin Arfa — Daten- und Software-Engineering-Beratung aus Basel. Orientierung bei Dateninitiativen, Systemintegration und Interoperabilität.',
      eyebrow: 'Die Tür steht offen',
      pageTitle: 'Sprechen wir',
      sub: 'Sie suchen strategische Orientierung bei Dateninitiativen, Systemintegration oder Interoperabilität? Briefings, halbfertige Ideen und Erstkontakte sind gleichermassen willkommen.',
      sectionLabel: '01 &mdash; Anfragen',
      sectionHeading: 'Nachricht senden',
      formLabel: 'Nachricht senden &middot; Antwort innert 48 h',
      successMessage: 'Nachricht gesendet &mdash; vielen Dank. Ich antworte innert 48 Stunden.',
      submit: 'Nachricht senden',
      fields: {
        name: { label: 'Name', placeholder: 'Ihr Name' },
        email: { label: 'E-Mail', placeholder: 'sie@beispiel.ch' },
        subject: { label: 'Betreff' },
        message: { label: 'Nachricht', placeholder: 'Erzählen Sie mir von Ihrem Projekt, Problem oder Ihrer Idee.' },
      },
      subjectOptions: [
        'Allgemeine Anfrage', 'Projekt / Beratung', 'HL7- / FHIR-Frage',
        'BIRD- / RegTech-Frage', 'Vortrag / Interview', 'Anderes',
      ],
      channelsLabel: 'Direkte Kanäle',
      officeLabel: 'Büro',
      office: [
        { k: 'Standort', v: 'Basel, Schweiz' },
        { k: 'Sprachen', v: 'Französisch &middot; Deutsch &middot; Englisch &middot; Spanisch' },
        { k: 'Firma', v: 'Arfa Digital Consulting' },
        { k: 'UID', v: '<span class="mono">CHE-294.585.543</span>' },
      ],
      hoursLabel: 'Bürozeiten',
      hours: [
        { k: 'Mo &ndash; Fr', v: '09:00 &ndash; 18:00 MEZ' },
        { k: 'Antwort', v: 'innert 48 Stunden' },
        { k: 'Telefonate', v: 'nach Vereinbarung' },
      ],
      quote: 'Ein Mensch liest Ihre Nachricht und antwortet &mdash; meist innert 48 Stunden, oft am selben Tag.',
      quoteAttr: 'Kein Newsletter, keine Autoantworten',
    },

    blog: {
      file: 'blog.html',
      title: 'Journal | Arfa Digital Consulting',
      description: 'Texte zu Interoperabilität im Gesundheitswesen, Data Engineering, Regulatory Technology und dem Weg von der Technik in die Beratung.',
      eyebrow: 'Gedanken &amp; Perspektiven',
      pageTitle: 'Journal',
      sub: 'Über Interoperabilität im Gesundheitswesen, Data Engineering, Regulatory Technology und den Weg von technischen Rollen in die digitale Beratung.',
      sectionLabel: '01 &mdash; Beiträge',
      sectionHeading: 'Aktuelle Texte',
      tag: 'Journal',
      filters: [
        { key: 'all', label: 'Alle' }, { key: 'tech', label: 'Technik' },
        { key: 'healthcare', label: 'Gesundheit' }, { key: 'career', label: 'Karriere' },
      ],
      englishOnlyNote: 'Die Journalbeiträge erscheinen auf Englisch.',
      ctaHeading: 'Etwas zu besprechen?',
      ctaBody: 'Wenn ein Beitrag eine Frage aufgeworfen hat oder Sie anderer Meinung sind, höre ich das gerne.',
      posts: [
        { file: 'blog/healthcare-data-pipelines.html', cats: 'tech healthcare', h: 'Building healthcare data pipelines with FHIR', p: 'Wie HL7 FHIR den Bau von Datenpipelines im Gesundheitswesen verändert &mdash; echte Interoperabilität bei aller Komplexität klinischer Datenmodelle.' },
        { file: 'blog/open-standards-regtech.html', cats: 'tech', h: 'Why open standards matter in RegTech', p: 'Offene Standards wie BIRD und SDMX verändern das regulatorische Reporting. Warum sie zählen und wie sie den Compliance-Aufwand senken.' },
        { file: 'blog/data-engineering-to-consulting.html', cats: 'career', h: 'From data engineering to digital consulting', p: 'Über den Weg vom Data Engineering und der ML-Forschung hin zur Leitung digitaler Beratungsvorhaben &mdash; und die Fähigkeiten, die beide Welten verbinden.' },
      ],
    },

    impressum: {
      file: 'impressum.html',
      title: 'Impressum | Arfa Digital Consulting',
      description: 'Impressum und Firmenangaben der Arfa Digital Consulting — Einzelunternehmen mit Sitz in Basel-Stadt, Schweiz.',
      eyebrow: 'Rechtliche Angaben',
      pageTitle: 'Impressum',
      sub: 'Impressum und Firmenangaben der Arfa Digital Consulting &mdash; ein Einzelunternehmen mit Sitz in Basel-Stadt, Schweiz.',
      sectionLabel: '01 &mdash; Rechtliche Angaben',
      sectionHeading: 'Firmenangaben',
      companyLabel: 'Das Unternehmen',
      company: [
        { k: 'Inhaber', v: 'Benjamin Arfa' },
        { k: 'Adresse', v: 'Grellingerstrasse 44<br>4052 Basel<br>Schweiz' },
        { k: 'Rechtsform', v: 'Einzelunternehmen' },
        { k: 'UID', v: '<span class="mono">CHE-294.585.543</span>' },
        { k: 'Registereintrag', v: 'Handelsregisteramt des Kantons Basel-Stadt' },
        { k: 'MWST', v: 'Befreit nach Art. 10 MWSTG' },
      ],
      contactLabel: 'Kontakt',
      purposeLabel: 'Zweck des Unternehmens',
      purpose: '<strong>Arfa Digital Consulting</strong> bezweckt die Förderung der digitalen Transformation durch IT- und KI-Lösungen, die Optimierung von IT-Infrastrukturen, Software- und App-Entwicklung, Cybersicherheit, Datenschutz und Datenanalyse, IT-Beratung und -Support sowie technischen Support.',
      repLabel: 'Zeichnungsberechtigung',
      rep: 'Benjamin Arfa, französischer Staatsangehöriger, mit Einzelunterschrift.',
      liabilityLabel: 'Haftungsausschluss',
      liability: 'Die Inhalte dieser Website wurden mit grösster Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Angaben kann jedoch keine Gewähr übernommen werden. Für Schäden aus der Nutzung dieser Website wird keine Haftung übernommen.',
      copyrightLabel: 'Urheberrecht',
      copyright: '&copy; 2026 Arfa Digital Consulting. Alle Rechte vorbehalten. Inhalt und Gestaltung dieser Website sind urheberrechtlich geschützt.',
    },

    notfound: {
      file: '404.html',
      title: '404 | Arfa Digital Consulting',
      description: 'Diese Seite konnte nicht gefunden werden.',
      eyebrow: 'Fehler 404',
      pageTitle: 'Seite nicht gefunden',
      sub: 'Die gesuchte Seite existiert nicht, wurde verschoben oder hat vielleicht nie existiert.',
      backHome: 'Zur Startseite',
      viewProjects: 'Projekte ansehen',
      sectionLabel: '01 &mdash; Anderswo',
      sectionHeading: 'Vielleicht eine davon',
      tag: 'Seite',
      cards: [
        { h: 'Über mich', p: 'Der Gründer, der Leistungsausweis und der Werdegang hinter der Beratung.', file: 'about.html' },
        { h: 'Projekte', p: 'Open-Source-Werkzeuge für regulatorisches Reporting, Schweizer Rechtsdaten und Interoperabilität im Gesundheitswesen.', file: 'projects.html' },
        { h: 'Kontakt', p: 'Briefings, halbfertige Ideen und Erstkontakte sind gleichermassen willkommen.', file: 'contact.html' },
      ],
    },
  },

  shared: {
    pillars: [
      { label: 'Säule 01', h: 'Software Engineering', p: 'Skalierbare Datenanwendungen und Systemintegration. Vom Requirements Engineering bis zum Betrieb.', tags: ['Python', 'Docker', 'APIs'] },
      { label: 'Säule 02', h: 'Interoperabilität im Gesundheitswesen', p: 'Technical Manager bei HL7 Schweiz (FHIR-CH), treibend bei der Standardisierung von Gesundheitsdaten. Semantische Integration und Stammdatenmanagement.', tags: ['HL7 FHIR', 'MDM', 'Integration'] },
      { label: 'Säule 03', h: 'Metadatenarchitektur', p: 'Metadatenmanagement und Datenarchitektur. Robuste, geschäftsorientierte Systeme mit wirksamer Governance.', tags: ['SDMX', 'BIRD', 'Governance'] },
    ],
    involvementCards: [
      { label: 'Technical Manager', h: 'HL7 Schweiz', p: 'Standardisierung von Gesundheitsdaten für FHIR-CH &mdash; Umsetzungsleitfäden, Arbeitsgruppen zur Interoperabilität und Schweizer Standards für den Gesundheitsdatenaustausch.', links: [{ t: 'hl7.ch', href: 'https://www.hl7.ch/de/' }, { t: 'fhir.ch', href: 'https://fhir.ch' }] },
      { label: 'Head of Development', h: 'BIRD Software Solutions', p: 'Leitung von Softwareentwicklung und technischer Strategie für Regulatory Technology &mdash; quelloffene Dateninfrastruktur nach dem BIRD-Standard.', links: [{ t: 'GitHub', href: 'https://github.com/BIRD-Software-Solutions' }] },
      { label: 'Mitgründer', h: 'BIRDBench Ltd', p: 'Offene, benchmarkgetriebene Ansätze für Regulatory Technology im BIRD-Ökosystem.', links: [] },
      { label: 'Contributor', h: 'Eclipse Foundation', p: 'Open-Source-Beiträge über Eclipse EFBT &mdash; Werkzeuge für regulatorisches Reporting, offen und herstellerneutral entwickelt.', links: [{ t: 'eclipse.org', href: 'https://www.eclipse.org' }] },
    ],
  },
};
