// =====================================================================
// Français (Suisse romande).
//
// Les clés absentes reprennent l'anglais ; le build les signale.
// NE PAS traduire : `file`, les URL, les attributs `name` du formulaire.
// =====================================================================

export default {
  locale: 'fr',
  localeName: 'Français',
  htmlLang: 'fr-CH',

  brand: { sub: 'Conseil', location: 'Bâle, Suisse' },

  nav: { menu: 'Menu', services: 'Prestations', work: 'Travaux', about: 'À propos', enquire: 'Contact' },

  ui: {
    skip: 'Aller au contenu',
    closeMenu: 'Fermer le menu',
    toggleTheme: 'Changer de thème',
    language: 'Langue',
    share: 'Partager cette page',
    shareEmail: 'E-mail',
    copyLink: 'Copier le lien',
    copied: 'Copié',
    allArticles: 'Tous les articles',
    allServices: 'Toutes les prestations',
    allProjects: 'Tous les projets',
    allInvolvement: 'Tous les engagements',
    aboutFounder: 'À propos du fondateur',
    getInTouch: 'Contact',
    startConversation: 'Entamer la discussion',
    read: 'Lire',
    searchArticles: 'Rechercher un article',
    filterAll: 'Tous',
  },

  menu: {
    home: 'Accueil', practice: 'Le cabinet', workGroup: 'Travaux', elsewhere: 'Ailleurs',
    projects: 'Projets', journal: 'Journal', involvement: 'Engagement',
    note: 'Outils open source pour le reporting réglementaire, les données juridiques suisses et l’interopérabilité en santé.',
    enquireNow: 'Me contacter', impressum: 'Mentions légales',
  },

  footer: {
    blurb: 'Intégration de données, gouvernance et gestion du cycle de vie pour les secteurs réglementés. Bâle, Suisse.',
    colPractice: 'Cabinet', colWork: 'Travaux', colContact: 'Contact',
    rights: 'Tous droits réservés',
  },

  pages: {
    index: {
      file: 'index.html',
      title: 'Arfa Digital Consulting | Infrastructure de données pour secteurs réglementés',
      description: 'Arfa Digital Consulting — intégration de données, gouvernance et interopérabilité en santé depuis Bâle, Suisse. Fondé par Benjamin Arfa.',
      eyebrow: 'Conseil depuis Bâle, Suisse',
      display: 'Infrastructure de données pour secteurs réglementés',
      lead: 'Conseil spécialisé en intégration de données, gouvernance et gestion du cycle de vie &mdash; pour la technologie réglementaire et la santé, là où l’exactitude n’est pas optionnelle.',
      facts: [
        { k: 'Basé à', v: 'Bâle, Suisse' },
        { k: 'Langues', v: 'Français &middot; Allemand &middot; Anglais &middot; Espagnol' },
        { k: 'Statut', v: 'Disponible pour des mandats', dot: true },
      ],
      practiceLabel: '01 &mdash; Le cabinet',
      practiceHeading: 'Une ingénierie qui résiste à l’audit',
      practiceBody: [
        'Arfa Digital Consulting accompagne la transformation numérique par des <strong>solutions informatiques et d’IA, le développement logiciel, l’analyse de données et le conseil stratégique</strong> &mdash; adaptés aux contextes réglementaires suisse et européen.',
        'Derrière le cabinet : <strong>Benjamin Arfa</strong>, ingénieur, Technical Manager chez HL7 Suisse et cofondateur de <strong>BIRDBench Ltd</strong>. Neuf ans de modélisation de métadonnées pour la BCE et l’OFS, de modélisation FHIR pour la santé suisse, d’outils open source BIRD et de données de production en sciences de la vie.',
      ],
      quote: 'Une infrastructure partagée plutôt que des silos sous licence. Des règles transparentes plutôt que des boîtes noires.',
      quoteAttr: 'Sur la construction d’outils réglementaires ouverts',
      servicesLabel: '02 &mdash; Prestations',
      servicesHeading: 'Trois piliers',
      workLabel: '03 &mdash; Travaux choisis',
      workHeading: 'Open source et production',
      involvementLabel: '04 &mdash; Engagement',
      involvementHeading: 'Normes et communauté',
      ctaHeading: 'Travaillons ensemble',
      ctaBody: 'Vous cherchez un accompagnement sur vos initiatives de données, l’intégration de systèmes ou l’interopérabilité ? Chaque mandat commence par un entretien exploratoire.',
    },

    about: {
      file: 'about.html',
      title: 'À propos | Benjamin Arfa, Arfa Digital Consulting',
      description: 'Benjamin Arfa — ingénieur données et logiciel à Bâle. Neuf ans en santé, technologie réglementaire et gouvernance des données.',
      eyebrow: 'Le fondateur',
      pageTitle: 'Benjamin Arfa',
      sub: 'Ingénieur données et logiciel à Bâle. Neuf ans en santé, technologie réglementaire et gouvernance des données en entreprise &mdash; fondateur d’Arfa Digital Consulting, cofondateur de BIRDBench Ltd.',
      bgLabel: '01 &mdash; Parcours',
      bgHeading: 'Parcours professionnel',
      bgBody: [
        'Je suis spécialisé en <strong>intégration de données</strong>, <strong>gouvernance</strong> et <strong>gestion du cycle de vie</strong> dans la technologie réglementaire et la santé. En plus de neuf ans, j’ai développé une expertise approfondie dans la mise en œuvre de stratégies de données et de solutions techniques qui résistent à l’examen.',
        'En <strong>stratégie et architecture de données</strong>, je me concentre sur une gestion complète du cycle de vie par une modélisation efficace et une mise en œuvre technique rigoureuse &mdash; des systèmes robustes, alignés sur le métier, et des organisations réellement pilotées par la donnée.',
        'Mon travail technique couvre l’<strong>ingénierie des exigences</strong>, en pont entre les équipes métier et techniques, et le <strong>génie logiciel</strong> pour des applications de données évolutives. Comme <strong>Technical Manager chez HL7 Suisse</strong> (FHIR-CH), je contribue à la normalisation des données de santé. Cofondateur de <strong>BIRDBench Ltd</strong>, j’apporte de l’innovation à la RegTech ; comme <strong>contributeur Eclipse</strong>, je développe des outils réglementaires au grand jour.',
      ],
      glanceLabel: 'En bref',
      glance: [
        { k: 'Basé à', v: 'Bâle, Suisse' },
        { k: 'Langues', v: 'Français &middot; Allemand &middot; Anglais &middot; Espagnol' },
        { k: 'Normes', v: 'HL7 FHIR &middot; SDMX &middot; BIRD' },
        { k: 'Cofondateur', v: 'BIRDBench Ltd' },
        { k: 'Open source', v: 'Contributeur de l’Eclipse Foundation' },
      ],
      quote: 'L’infrastructure partagée vaut mieux que les silos sous licence &mdash; les règles transparentes mieux que les boîtes noires.',
      quoteAttr: 'Pourquoi les outils sont open source',
      careerLabel: '02 &mdash; Carrière',
      careerHeading: 'Parcours',
      career: [
        { when: 'Mai 2026 &mdash;', role: 'Cofondateur', where: 'BIRDBench Ltd', desc: 'Apporter de l’innovation à la RegTech.' },
        { when: 'Avr. 2026 &mdash;', role: 'Technical Manager', where: 'HL7 Suisse', desc: 'Normalisation des données de santé pour FHIR-CH &mdash; guides de mise en œuvre, groupes de travail sur l’interopérabilité et normes suisses d’échange de données de santé.' },
        { when: 'Oct. 2025 &mdash;', role: 'Analyste métier', where: 'Bachem', desc: 'Ingénierie des exigences pour les données pharmaceutiques et biotechnologiques en production &mdash; intégration de systèmes, gestion du cycle de vie et reporting opérationnel en R&amp;D et production.' },
        { when: 'Févr. 2025 &mdash;', role: 'Head of Development', where: 'BIRD Software Solutions', desc: 'Direction du développement logiciel et de la stratégie technique en technologie réglementaire &mdash; infrastructure de données open source alignée sur la norme BIRD.' },
        { when: '2022 &ndash; 2024', role: 'Product Owner, données &amp; intégration', where: 'Bluespace Ventures', desc: 'Intégration sémantique, modélisation FHIR, cadres MDM. Contributions à HL7 Suisse et au SNOMED French Translation Group.' },
        { when: '2020 &ndash; 2022', role: 'Analyste de recherche, métadonnées', where: 'BCE &amp; OFS', desc: 'Modélisation de métadonnées pour la supervision bancaire au sein de l’équipe BIRD/SDD, méthodologie SDMX, automatisation et intégration d’API pour les référentiels de métadonnées.' },
        { when: '2017 &ndash; 2020', role: 'Data scientist &amp; chercheur ML', where: 'RWTH Aachen &middot; rheindata &middot; CWD &middot; Boralex', desc: 'Recherche en apprentissage automatique, analyse exploratoire et applications pilotées par les données dans l’éolien et l’industrie.' },
      ],
      skillsLabel: '03 &mdash; Compétences',
      skillsHeading: 'Compétences clés',
      skills: [
        { label: 'Données', h: 'Données &amp; analytique', tags: ['Intégration de données', 'Gouvernance', 'Modélisation', 'Apprentissage automatique', 'ETL / ELT'] },
        { label: 'Développement', h: 'Ingénierie', tags: ['Python', 'Go', 'Docker', 'API REST', 'Cloud'] },
        { label: 'Normes', h: 'Santé &amp; normes', tags: ['HL7 FHIR', 'SDMX', 'MDM', 'Interopérabilité', 'BIRD'] },
      ],
      personalLabel: '04 &mdash; Hors du bureau',
      personalHeading: 'La personne derrière',
      personalBody: [
        'C’est <strong>Benni</strong> &mdash; une âme franco-germano-arabe, actuellement à Bâle.',
        'La musique est ma passion, le logiciel mon métier, et l’écriture m’accompagne depuis la cinquième année de gymnase. J’ai commencé par le dessin, la peinture et la calligraphie, puis est venue la poésie. Aujourd’hui j’écris de la prosodie et je prends la parole de temps à autre.',
        'J’aime commenter les sujets liés à la <strong>souveraineté, la technologie et la solidarité</strong>.',
      ],
      personal: [
        { k: 'Musique', v: 'jouer &middot; écouter &middot; improviser' },
        { k: 'Logiciel', v: 'le métier au quotidien' },
        { k: 'Écriture', v: 'poésie &middot; prosodie' },
        { k: 'Intérêts', v: 'souveraineté &middot; technologie &middot; solidarité' },
      ],
      ctaHeading: 'Envie de collaborer ?',
      ctaBody: 'Toujours heureux d’échanger avec des pairs sur les enjeux de données et les opportunités.',
    },

    services: {
      file: 'services.html',
      title: 'Prestations | Arfa Digital Consulting',
      description: 'Génie logiciel, interopérabilité en santé et architecture de métadonnées — conseil spécialisé pour les contextes réglementaires suisse et européen.',
      eyebrow: 'Ce que je propose',
      pageTitle: 'Prestations',
      sub: 'Arfa Digital Consulting accompagne la transformation numérique par des solutions informatiques et d’IA, le développement logiciel, l’analyse de données et le conseil stratégique &mdash; adaptés aux contextes réglementaires suisse et européen.',
      pillarsLabel: '01 &mdash; Prestations spécialisées',
      pillarsHeading: 'Trois piliers',
      pillars: [
        { label: 'Pilier 01 &mdash; Génie logiciel', body: 'Applications de données évolutives et intégration de systèmes. De l’ingénierie des exigences au déploiement, en pont entre métier et technique.', tags: ['Développement sur mesure', 'Conception d’API', 'Conteneurisation Docker', 'Ingénierie des exigences', 'Cycle de vie cloud'] },
        { label: 'Pilier 02 &mdash; Interopérabilité en santé', body: 'Technical Manager chez <strong>HL7 Suisse</strong> (FHIR-CH), moteur de la normalisation des données de santé. Spécialisé en intégration sémantique et gestion des données de référence.', tags: ['Mise en œuvre HL7 FHIR', 'Intégration sémantique', 'Données de référence (MDM)', 'Normalisation en santé', 'Intégration de systèmes'] },
        { label: 'Pilier 03 &mdash; Architecture de métadonnées', body: 'Gestion complète des métadonnées et conception d’architecture de données. Des systèmes robustes, alignés sur le métier, avec des cadres de gouvernance efficaces.', tags: ['Gestion des métadonnées', 'Gouvernance des données', 'SDMX &amp; BIRD', 'Stratégie de cycle de vie', 'Solutions alignées métier'] },
      ],
      processLabel: '02 &mdash; Collaboration',
      processHeading: 'Ma façon de travailler',
      process: [
        { label: 'Étape 01', h: 'Comprendre', p: 'Cerner vos enjeux et votre contexte métier &mdash; entretien exploratoire, cartographie des parties prenantes.' },
        { label: 'Étape 02', h: 'Concevoir', p: 'Architecturer des solutions alignées sur vos objectifs &mdash; modèles de données, topologie d’intégration, gouvernance.' },
        { label: 'Étape 03', h: 'Développer', p: 'Construire des implémentations robustes et évolutives &mdash; Python, Go, FHIR, Docker, CI.' },
        { label: 'Étape 04', h: 'Livrer', p: 'Déployer et accompagner votre solution &mdash; transfert, documentation, mandat de conseil.' },
      ],
      extrasLabel: '03 &mdash; Également disponible',
      extrasHeading: 'Prestations complémentaires',
      extrasTag: 'Complément',
      extras: [
        { h: 'Conseil informatique', p: 'Accompagnement stratégique sur les décisions technologiques, l’optimisation d’infrastructure et la transformation numérique.' },
        { h: 'Communication plurilingue', p: 'Faire le pont entre les contextes français, allemand, anglais et espagnol.' },
        { h: 'Modélisation de données', p: 'Modélisation conceptuelle, logique et physique pour bases de données et entrepôts.' },
        { h: 'Conseil en ML', p: 'Stratégie d’apprentissage automatique, accompagnement du développement de modèles et architecture de solutions d’IA.' },
      ],
      quote: 'Chaque mandat commence par un entretien exploratoire &mdash; et une réponse honnête sur le fait que je sois, ou non, la bonne personne.',
      quoteAttr: 'Comment débutent les mandats',
      faqLabel: '04 &mdash; Questions',
      faqHeading: 'Questions fréquentes',
      faq: [
        { q: 'Sur quels types de projets travaillez-vous ?', a: 'Ingénierie des données, interopérabilité en santé et technologie réglementaire. Cela va des pipelines d’intégration HL7 FHIR et des outils BIRD pour le reporting réglementaire aux architectures de métadonnées et aux solutions de données de référence.' },
        { q: 'Travaillez-vous avec des clients hors de Suisse ?', a: 'Oui. Je suis basé à Bâle mais je collabore régulièrement avec des équipes dans toute l’Europe et à distance avec des clients internationaux. Mon parcours plurilingue (français, allemand, anglais, espagnol) facilite la communication entre équipes hétérogènes.' },
        { q: 'Quel est votre modèle de mandat habituel ?', a: 'Les mandats suivent quatre étapes : comprendre, concevoir, développer, livrer. Je propose du conseil au projet avec des livrables clairs ainsi que des mandats de conseil continus. Chaque mandat commence par un entretien exploratoire.' },
        { q: 'Intervenez-vous sur des systèmes existants ou uniquement sur du neuf ?', a: 'Les deux. Une part importante de mon travail consiste à moderniser des systèmes existants, améliorer des pipelines et intégrer de nouvelles normes dans une infrastructure établie &mdash; y compris HL7 v2, des exports propriétaires de dossiers patients et des cadres de reporting en place.' },
        { q: 'Comment traitez-vous la protection des données et la conformité ?', a: 'La protection des données est intégrée dès la conception : exigences suisses et européennes, conformité RGPD, confidentialité des données de santé et pratiques de traitement sécurisé pour le reporting réglementaire.' },
      ],
      ctaHeading: 'Prêt à lancer un projet ?',
      ctaBody: 'Discutons de la façon dont je peux vous aider à atteindre vos objectifs de données et de technologie. Cahiers des charges, idées encore floues et premiers contacts sont tous bienvenus.',
    },

    projects: {
      file: 'projects.html',
      title: 'Projets | Arfa Digital Consulting',
      description: 'Outils open source et applications de données en technologie réglementaire, santé et GovTech — par Benjamin Arfa.',
      eyebrow: 'Ce que j’ai construit',
      pageTitle: 'Projets',
      sub: 'Outils open source, applications de données et génie logiciel en technologie réglementaire, santé, GovTech &mdash; et un jeu de week-end à l’occasion.',
      currentLabel: '01 &mdash; En cours',
      currentHeading: 'Open source et production',
      quote: 'Le reporting réglementaire concerne chaque banque, et à travers elles tout le monde. C’est précisément pourquoi ces outils se construisent au grand jour.',
      quoteAttr: 'Sur les normes ouvertes',
      archiveLabel: '02 &mdash; Archives',
      archiveHeading: 'Travaux antérieurs',
      archiveTag: 'Archives',
      ctaHeading: 'Envie de collaborer ?',
      ctaBody: 'Toujours ouvert à discuter de nouveaux projets, de contributions open source ou d’opportunités de collaboration.',
      visitDashboard: 'Voir le tableau de bord',
      visitSite: 'Visiter consultaition.ch',
      viewGitHub: 'Voir sur GitHub',
      entries: [
        {
          anchor: 'swiss-law', n: '01', role: 'Mainteneur &middot; GovTech',
          h: 'Swiss Law Collection',
          kicker: 'Le droit fédéral et cantonal suisse comme jeu de données interrogeable',
          body: [
            'Un tableau de bord sur la législation fédérale et cantonale suisse, ainsi qu’une API statique en lecture seule aux formats JSON, CSV et SDMX servie directement depuis GitHub Pages. Les domaines juridiques sont harmonisés entre la Confédération et les 26 cantons, ce qui rend les actes fédéraux et cantonaux comparables sur un même axe.',
            'Publier la loi comme donnée plutôt qu’en PDF permet de tester les systèmes en aval, et les flux Atom et RSS font d’une modification législative quelque chose auquel un logiciel peut s’abonner.',
          ],
          details: [
            { k: 'Couverture', v: '34&#8239;443 actes &mdash; Confédération et 26 cantons' },
            { k: 'Articles', v: '824&#8239;663 indexés' },
            { k: 'Formats', v: 'JSON &middot; CSV &middot; SDMX' },
            { k: 'Sources', v: 'Fedlex (fédéral) &middot; LexFind (cantonal)' },
            { k: 'Vérification', v: 'Rapprochement publié avec BADAC et chstat' },
            { k: 'Pipeline', v: '<a class="link" href="https://github.com/benjamin-arfa/swiss-law" target="_blank" rel="noopener">github.com/benjamin-arfa/swiss-law</a>' },
          ],
          tags: ['Open data', 'SDMX', 'API JSON', 'Python'],
          href: 'https://swiss-law-as-source.github.io/', cta: 'visitDashboard',
        },
        {
          anchor: 'consultaition', n: '02', role: 'Mainteneur &middot; GovTech',
          h: 'consultaition',
          kicker: 'Générateur de rapports de consultation fédérale suisse',
          body: [
            'Automatise la rédaction des <em>rapports de résultats</em> de consultation fédérale à partir de données Excel structurées. Optimisation LLM indépendante du fournisseur, calibrée sur de véritables données de consultation fédérale &mdash; sans enfermement propriétaire.',
          ],
          details: [
            { k: 'Éditeur', v: 'Canvas interactif, paragraphe par paragraphe' },
            { k: 'API', v: 'Point d’accès REST pour la génération programmatique' },
            { k: 'Langues', v: 'Allemand &middot; Français &middot; Italien' },
            { k: 'Sortie', v: 'Gestion des notes de bas de page et export' },
          ],
          tags: ['Python', 'FastAPI', 'LLM', 'GovTech'],
          href: 'https://consultaition.ch', cta: 'visitSite',
        },
        {
          anchor: 'freebird', n: '03', role: 'Contributeur &middot; RegTech',
          h: 'Eclipse FreeBIRD tools',
          kicker: 'Des outils pour rendre BIRD accessible comme norme ouverte',
          body: [
            'Une boîte à outils open source pour le Banks’ Integrated Reporting Dictionary &mdash; la norme qui définit les règles et modèles de reporting utilisés par les banques européennes pour transmettre leurs données aux autorités de surveillance.',
          ],
          details: [
            { k: 'Outils', v: 'Interface pour dictionnaires et correspondances' },
            { k: 'Exécution', v: 'Conteneurisation Docker' },
            { k: 'Modèles', v: 'Valider et transformer les modèles BIRD' },
            { k: 'Installation', v: '<span class="mono">pip install pybirdai</span>' },
          ],
          tags: ['Python', 'Docker', 'NLP', 'RegTech'],
          href: 'https://github.com/eclipse-efbt/efbt', cta: 'viewGitHub',
        },
      ],
      archive: [
        { h: 'px-reader', p: 'Application Python qui analyse les px-cubes de l’Office fédéral de la statistique. Conversion en données liées, importables dans des triple stores RDF.', href: 'https://github.com/benjamin-arfa/px-reader' },
        { h: 'go-detective', p: 'Application de bureau native (Go et Wails) pour les contrôles KYC, le filtrage AML et la vérification PEP/sanctions. Backend Supabase.', href: 'https://github.com/benjamin-arfa/go-detective' },
        { h: 'static-gen', p: 'Transforme du contenu en sites HTML statiques. Templating sur mesure et automatisation de build.', href: 'https://github.com/benjamin-arfa/static-gen' },
        { h: 'pyroids', p: 'Implémentation Pygame du classique Asteroids : déplacement physique, fragmentation des astéroïdes, difficulté dynamique.', href: 'https://github.com/benjamin-arfa/pyroids' },
      ],
    },

    involvement: {
      file: 'involvement.html',
      title: 'Engagement | Arfa Digital Consulting',
      description: 'Travaux de normalisation et communautaires — HL7 Suisse, fhir.ch, BIRD Software Solutions, Eclipse Foundation et BIRDBench Ltd.',
      eyebrow: 'Communauté &amp; contributions',
      pageTitle: 'Engagement',
      sub: 'Contributions aux communautés professionnelles et aux organismes de normalisation &mdash; en coopération avec <a class="link" href="https://www.eseha.ch" target="_blank" rel="noopener">ESEHA</a>, HL7 Suisse, l’Eclipse Foundation et l’écosystème BIRD.',
      orgsLabel: '01 &mdash; Organisations',
      orgsHeading: 'Où je contribue',
      quote: 'Le travail de normalisation est lent, ingrat &mdash; et c’est la seule chose qui permette aux systèmes de se parler encore dix ans plus tard.',
      quoteAttr: 'Pourquoi les normes',
      whyLabel: '02 &mdash; Motivations',
      whyHeading: 'Pourquoi la communauté compte',
      whyTag: 'Pourquoi',
      why: [
        { h: 'Partage des savoirs', p: 'Partager son expérience et apprendre de ses pairs accélère l’innovation et aide à résoudre ensemble des problèmes complexes.' },
        { h: 'Élaboration de normes', p: 'Contribuer aux normes garantit l’interopérabilité, réduit la fragmentation et pose les bases de solutions durables.' },
        { h: 'Impact sur le secteur', p: 'La participation active aux communautés professionnelles façonne l’avenir de la gestion des données de santé et de l’adoption technologique.' },
      ],
      ctaHeading: 'Envie d’échanger ?',
      ctaBody: 'Toujours heureux d’échanger &mdash; sur les enjeux de données, le partage de savoirs ou d’éventuelles collaborations.',
      entries: [
        {
          anchor: 'hl7', n: '01', role: 'Technical Manager', h: 'HL7 Suisse',
          kicker: 'Health Level Seven &mdash; l’autorité mondiale de l’interopérabilité en santé',
          body: ['Technical Manager chez HL7 Suisse (FHIR-CH), moteur de la normalisation des données de santé en Suisse. HL7 définit les normes mondiales d’interopérabilité des systèmes d’information de santé ; <strong>hl7.ch</strong> est l’affilié suisse et <strong>fhir.ch</strong> publie les guides de mise en œuvre FHIR suisses.'],
          details: [
            { k: 'Association', v: '<a class="link" href="https://www.hl7.ch/de/" target="_blank" rel="noopener">hl7.ch</a>' },
            { k: 'Guides', v: '<a class="link" href="https://fhir.ch" target="_blank" rel="noopener">fhir.ch</a>' },
            { k: 'Axes', v: 'Guides de mise en œuvre FHIR, groupes de travail sur l’interopérabilité, normes suisses d’échange de données de santé' },
          ],
          tags: ['HL7 FHIR', 'Interopérabilité', 'Normes'],
          href: 'https://fhir.ch', cta: 'Visiter fhir.ch',
        },
        {
          anchor: 'bird-software', n: '02', role: 'Head of Development', h: 'BIRD Software Solutions',
          kicker: 'Infrastructure de données réglementaires fondée sur une norme ouverte',
          body: ['Direction du développement logiciel et de la stratégie technique en technologie réglementaire &mdash; infrastructure de données open source alignée sur la norme BIRD, le Banks’ Integrated Reporting Dictionary du reporting prudentiel européen.'],
          details: [],
          tags: ['RegTech', 'BIRD', 'Open source'],
          href: 'https://github.com/BIRD-Software-Solutions', cta: 'Voir sur GitHub',
        },
        {
          anchor: 'eclipse', n: '03', role: 'Contributeur', h: 'Eclipse Foundation',
          kicker: 'L’open source comme bien public',
          body: ['Contributeur de l’Eclipse Foundation via <strong>Eclipse EFBT</strong>, foyer des outils FreeBIRD. Le reporting réglementaire concerne chaque banque et, à travers elles, tout le monde. Construire ces outils au grand jour, sous une gouvernance indépendante, c’est choisir l’infrastructure partagée plutôt que les silos sous licence, et les règles transparentes plutôt que les boîtes noires.'],
          details: [],
          tags: ['Eclipse EFBT', 'Gouvernance ouverte', 'Documentation'],
          href: 'https://www.eclipse.org', cta: 'Visiter eclipse.org',
        },
        {
          anchor: 'birdbench', n: '04', role: 'Cofondateur', h: 'BIRDBench Ltd',
          kicker: 'Apporter de l’innovation à la RegTech',
          body: ['Cofondateur de BIRDBench Ltd &mdash; des approches ouvertes et pilotées par le benchmarking pour la technologie réglementaire, au sein de l’écosystème BIRD.'],
          details: [],
          tags: ['RegTech', 'Benchmarking'],
          href: 'https://github.com/BIRD-Software-Solutions', cta: 'Travaux liés',
        },
        {
          anchor: 'cmda', n: '05', role: 'Membre', h: 'CMDA',
          kicker: 'Conseil Mondial de la Diaspora Alg&eacute;rienne',
          body: ['Membre du Conseil Mondial de la Diaspora Algérienne &mdash; représentation de la diaspora, échanges culturels, collaboration internationale et initiatives communautaires.'],
          details: [],
          tags: ['Communauté', 'Échanges culturels'],
          href: 'https://cmda.world', cta: 'Visiter cmda.world',
        },
      ],
    },

    contact: {
      file: 'contact.html',
      title: 'Contact | Arfa Digital Consulting',
      description: 'Contacter Benjamin Arfa — conseil en ingénierie des données et du logiciel depuis Bâle. Accompagnement sur les initiatives de données, l’intégration et l’interopérabilité.',
      eyebrow: 'La porte est ouverte',
      pageTitle: 'Parlons-en',
      sub: 'Vous cherchez un accompagnement stratégique sur vos initiatives de données, l’intégration de systèmes ou l’interopérabilité ? Cahiers des charges, idées encore floues et premiers contacts sont tous bienvenus.',
      sectionLabel: '01 &mdash; Demandes',
      sectionHeading: 'Envoyer un message',
      formLabel: 'Envoyer un message &middot; réponse sous 48 h',
      successMessage: 'Message envoyé &mdash; merci. Je réponds sous 48 heures.',
      submit: 'Envoyer le message',
      fields: {
        name: { label: 'Nom', placeholder: 'Votre nom' },
        email: { label: 'E-mail', placeholder: 'vous@exemple.ch' },
        subject: { label: 'Objet' },
        message: { label: 'Message', placeholder: 'Parlez-moi de votre projet, de votre problème ou de votre idée.' },
      },
      subjectOptions: [
        'Demande générale', 'Projet / conseil', 'Question HL7 / FHIR',
        'Question BIRD / RegTech', 'Conférence / interview', 'Autre',
      ],
      channelsLabel: 'Canaux directs',
      officeLabel: 'Bureau',
      office: [
        { k: 'Lieu', v: 'Bâle, Suisse' },
        { k: 'Langues', v: 'Français &middot; Allemand &middot; Anglais &middot; Espagnol' },
        { k: 'Société', v: 'Arfa Digital Consulting' },
        { k: 'IDE', v: '<span class="mono">CHE-294.585.543</span>' },
      ],
      hoursLabel: 'Horaires',
      hours: [
        { k: 'Lun &ndash; ven', v: '09:00 &ndash; 18:00 HEC' },
        { k: 'Réponse', v: 'sous 48 heures' },
        { k: 'Appels', v: 'sur rendez-vous' },
      ],
      quote: 'Une personne lit votre message et vous répond &mdash; généralement sous 48 heures, souvent le jour même.',
      quoteAttr: 'Pas de newsletter, pas de réponse automatique',
    },

    blog: {
      file: 'blog.html',
      title: 'Journal | Arfa Digital Consulting',
      description: 'Textes sur l’interopérabilité en santé, l’ingénierie des données, la technologie réglementaire et le passage de la technique au conseil.',
      eyebrow: 'Réflexions &amp; perspectives',
      pageTitle: 'Journal',
      sub: 'Sur l’interopérabilité en santé, l’ingénierie des données, la technologie réglementaire et le parcours des rôles techniques vers le conseil numérique.',
      sectionLabel: '01 &mdash; Articles',
      sectionHeading: 'Textes récents',
      tag: 'Journal',
      filters: [
        { key: 'all', label: 'Tous' }, { key: 'tech', label: 'Technique' },
        { key: 'healthcare', label: 'Santé' }, { key: 'career', label: 'Carrière' },
      ],
      englishOnlyNote: 'Les articles du journal sont publiés en anglais.',
      ctaHeading: 'Une remarque ?',
      ctaBody: 'Si un article a soulevé une question, ou si vous n’êtes pas d’accord, cela m’intéresse sincèrement.',
      posts: [
        { file: 'blog/healthcare-data-pipelines.html', cats: 'tech healthcare', h: 'Building healthcare data pipelines with FHIR', p: 'Comment HL7 FHIR transforme la construction de pipelines de données en santé &mdash; une vraie interopérabilité malgré la complexité des modèles cliniques.' },
        { file: 'blog/open-standards-regtech.html', cats: 'tech', h: 'Why open standards matter in RegTech', p: 'Les normes ouvertes comme BIRD et SDMX transforment le reporting réglementaire. Pourquoi elles comptent et comment elles allègent la charge de conformité.' },
        { file: 'blog/data-engineering-to-consulting.html', cats: 'career', h: 'From data engineering to digital consulting', p: 'Réflexions sur le passage de l’ingénierie des données et de la recherche en ML à la conduite de projets de conseil numérique.' },
      ],
    },

    impressum: {
      file: 'impressum.html',
      title: 'Mentions légales | Arfa Digital Consulting',
      description: 'Mentions légales et informations sur Arfa Digital Consulting — entreprise individuelle inscrite à Bâle-Ville, Suisse.',
      eyebrow: 'Informations légales',
      pageTitle: 'Mentions légales',
      sub: 'Mentions légales et informations sur Arfa Digital Consulting &mdash; une entreprise individuelle inscrite à Bâle-Ville, Suisse.',
      sectionLabel: '01 &mdash; Mentions légales',
      sectionHeading: 'Informations sur la société',
      companyLabel: 'La société',
      company: [
        { k: 'Titulaire', v: 'Benjamin Arfa' },
        { k: 'Adresse', v: 'Grellingerstrasse 44<br>4052 Bâle<br>Suisse' },
        { k: 'Forme juridique', v: 'Entreprise individuelle' },
        { k: 'IDE', v: '<span class="mono">CHE-294.585.543</span>' },
        { k: 'Inscription', v: 'Registre du commerce du canton de Bâle-Ville' },
        { k: 'TVA', v: 'Exonérée selon l’art. 10 LTVA' },
      ],
      contactLabel: 'Contact',
      purposeLabel: 'But de la société',
      purpose: '<strong>Arfa Digital Consulting</strong> a pour but de promouvoir la transformation numérique par des solutions informatiques et d’IA, l’optimisation d’infrastructures informatiques, le développement de logiciels et d’applications, la cybersécurité, la protection et l’analyse de données, le conseil et le support informatiques, ainsi que le support technique.',
      repLabel: 'Signature autorisée',
      rep: 'Benjamin Arfa, ressortissant français, avec signature individuelle.',
      liabilityLabel: 'Clause de non-responsabilité',
      liability: 'Le contenu de ce site a été élaboré avec le plus grand soin. Aucune garantie n’est toutefois donnée quant à l’exactitude, l’exhaustivité ou l’actualité des informations fournies, et aucune responsabilité n’est assumée pour les dommages résultant de l’utilisation de ce site.',
      copyrightLabel: 'Droit d’auteur',
      copyright: '&copy; 2026 Arfa Digital Consulting. Tous droits réservés. Le contenu et la conception de ce site sont protégés par le droit d’auteur.',
    },

    notfound: {
      file: '404.html',
      title: '404 | Arfa Digital Consulting',
      description: 'Cette page est introuvable.',
      eyebrow: 'Erreur 404',
      pageTitle: 'Page introuvable',
      sub: 'La page recherchée n’existe pas, a été déplacée, ou n’a peut-être jamais existé.',
      backHome: 'Retour à l’accueil',
      viewProjects: 'Voir les projets',
      sectionLabel: '01 &mdash; Ailleurs',
      sectionHeading: 'Peut-être l’une de celles-ci',
      tag: 'Page',
      cards: [
        { h: 'À propos', p: 'Le fondateur, le parcours et l’expérience derrière le cabinet.', file: 'about.html' },
        { h: 'Projets', p: 'Outils open source pour le reporting réglementaire, les données juridiques suisses et l’interopérabilité en santé.', file: 'projects.html' },
        { h: 'Contact', p: 'Cahiers des charges, idées encore floues et premiers contacts sont tous bienvenus.', file: 'contact.html' },
      ],
    },
  },

  shared: {
    pillars: [
      { label: 'Pilier 01', h: 'Génie logiciel', p: 'Applications de données évolutives et intégration de systèmes. De l’ingénierie des exigences au déploiement.', tags: ['Python', 'Docker', 'API'] },
      { label: 'Pilier 02', h: 'Interopérabilité en santé', p: 'Technical Manager chez HL7 Suisse (FHIR-CH), moteur de la normalisation des données de santé. Intégration sémantique et données de référence.', tags: ['HL7 FHIR', 'MDM', 'Intégration'] },
      { label: 'Pilier 03', h: 'Architecture de métadonnées', p: 'Gestion des métadonnées et conception d’architecture de données. Systèmes robustes, alignés sur le métier, avec une gouvernance efficace.', tags: ['SDMX', 'BIRD', 'Gouvernance'] },
    ],
    involvementCards: [
      { label: 'Technical Manager', h: 'HL7 Suisse', p: 'Normalisation des données de santé pour FHIR-CH &mdash; guides de mise en œuvre, groupes de travail sur l’interopérabilité et normes suisses d’échange de données de santé.', links: [{ t: 'hl7.ch', href: 'https://www.hl7.ch/de/' }, { t: 'fhir.ch', href: 'https://fhir.ch' }] },
      { label: 'Head of Development', h: 'BIRD Software Solutions', p: 'Direction du développement logiciel et de la stratégie technique en technologie réglementaire &mdash; infrastructure open source alignée sur la norme BIRD.', links: [{ t: 'GitHub', href: 'https://github.com/BIRD-Software-Solutions' }] },
      { label: 'Cofondateur', h: 'BIRDBench Ltd', p: 'Des approches ouvertes et pilotées par le benchmarking pour la technologie réglementaire, au sein de l’écosystème BIRD.', links: [] },
      { label: 'Contributeur', h: 'Eclipse Foundation', p: 'Contributions open source via Eclipse EFBT &mdash; des outils de reporting réglementaire construits au grand jour, sous gouvernance indépendante.', links: [{ t: 'eclipse.org', href: 'https://www.eclipse.org' }] },
    ],
  },
};
